log:
  level: -1
  enablejson: false

config:
  http:
    bind-address: localhost
    port: 8080
    shutdown-timeout: 400ms
    static-content:
      - url-prefix: /apps
        indexes: false
        document-root: /Users/marioa.imperato

#    html-content: /templates/*

    server-context:
      path: /api
      context:
        sys-metrics-endpoint: /metrics
    mw-use:
      - mw-metrics
      - mw-tracing
      - mw-har-tracing
      - mw-error

  mw-handler-registry:
    mw-metrics:
#      namespace: example
#      subsystem: "08"
    mw-tracing:
      tags:
        - name: request.id
          type: header
          value: requestId
    mw-error:
      with-info: true
#      alphabet: "0123456789"
      span-tag: error.id
      header: x-errid
      status-code-policy:
        mode: if-unlisted
        ranges:
          - from: 200
            to: 299


